server:
  port: 8001
spring:
  application:
    name: life-time-eureka-server
eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: 8.155.10.223
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka
  server:
    wait-time-in-ms-when-sync-empty: 5
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 10000
    renewal-percent-threshold: 0.85
